# [General]
Background="Backgrounds/Wallpaper.jpg"

# [Theme]
Variant="moon"
DeclareTheme="false"
NewBase=""
NewSurface=""
NewOverlay=""
NewText=""
NewSubtle=""
NewAccent=""
NewAccent2=""
NewAccent3=""
