# [General]
Background = "Backgrounds/Wallpaper-Moon.jpg"

# [Theme]
Variant = "moon"
DeclareTheme = "false"
NewBase = ""
NewSurface = ""
NewOverlay = ""
NewText = ""
NewSubtle = ""
NewAccent = ""
NewAccent2 = ""
NewAccent3 = ""

# [Font]
Font = "Lilex Nerd Font Mono"
FontSize = ""
ForceFontSize = "false"

# [Locale]
Locale = ""
HourFormat = "hh:mm AP"
DateFormat = "ddd d, MMM yyyy"

# [Form]
FormPosition = ""

# [Other]
Margins = ""
Roundings = ""
